/** generated by kysely-migrate */
import { type ColumnType, type Generated, type Selectable, type Insertable, type Updateable } from "kysely";

type UnwrapColumnType<c> = c extends ColumnType<infer s, infer i, infer u> ? ColumnType<s, i | undefined, u> : ColumnType<c, c | undefined, c>;

export type Todos = {
    id: Generated<UnwrapColumnType<ColumnType<string, string | number | bigint, string | number | bigint>>>;
    title: string;
    user_id: Generated<UnwrapColumnType<ColumnType<string, string | number | bigint, string | number | bigint>>>;
    summary: string | null;
    completed: boolean | null;
};

export type TodosInsertable = Insertable<Todos>;

export type TodosSelectable = Selectable<Todos>;

export type TodosUpdateable = Updateable<Todos>;

export type Users = {
    id: Generated<number>;
    name: string;
    email: string;
    created_at: Generated<UnwrapColumnType<ColumnType<Date, Date | string, Date | string>>>;
};

export type UsersInsertable = Insertable<Users>;

export type UsersSelectable = Selectable<Users>;

export type UsersUpdateable = Updateable<Users>;

export interface DB {
    todos: Todos;
    users: Users;
}

