/** generated by kysely-migrate */
import type {Generated, ColumnType, Selectable, Insertable, Updateable} from "kysely";

type UnwrapColumnType<c> = c extends ColumnType<infer s, infer i, infer u> ? ColumnType<s, i | undefined, u> : ColumnType<c, c | undefined, c>;

export type Users = {
    id: Generated<number>;
    name: string;
    email: string;
    created_at: Generated<UnwrapColumnType<ColumnType<Date, Date | string, Date | string>>>;
};

export type UsersInsertable = Insertable<Users>;

export type UsersSelectable = Selectable<Users>;

export type UsersUpdateable = Updateable<Users>;

export interface DB {
    users: Users;
}

